default:
  image: grifart/php8.0-with-all-modules-and-various-tools

stages:
  - build
  - test

build.composer:
  stage: build
  script: composer install --ansi --no-interaction --prefer-dist
  artifacts:
    expire_in: 2 days
    paths:
      - vendor


test.tests:
  stage: test
  dependencies: [build.composer]
  script: composer run test


test.phpstan:
  stage: test
  dependencies: [build.composer]
  script: composer run phpstan


test.linter:
  stage: test
  dependencies: [build.composer]
  script: composer run verify-syntax
